using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DAL;
using BUS;
using DevExpress.Utils.Win;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid;
using System.Data.Linq;
using DevExpress.XtraReports.UI;
using ControlLocalizer;
using GUI.Libs;

namespace GUI
{
    public partial class f_pttoan : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        KetNoiDBDataContext db = new KetNoiDBDataContext();
        t_pttoan pttoan = new t_pttoan();

        //form
        public f_pttoan()
        {
            InitializeComponent();
            lblbo.Text = "";
            lbltiente.Text = "";
            rsearchtiente1.DataSource = new DAL.KetNoiDBDataContext().tientes;
            txttiente.Properties.DataSource = new DAL.KetNoiDBDataContext().tientes;

            btnmuccp.DataSource = new DAL.KetNoiDBDataContext().muccps;
            btncongviec1.DataSource = new DAL.KetNoiDBDataContext().congviecs;

            txtiddt.Properties.DataSource = new DAL.KetNoiDBDataContext().doituongs;
            try
            {
                var lst = from a in db.donvis
                          select new
                          {
                              id = a.id,
                              tendonvi = a.tendonvi,
                          };
                txtch.Properties.DataSource = lst;

            }

            catch
            {
            }
            // This line of code is generated by Data Source Configuration Wizard
            //txtloaithu.Properties.DataSource = new DAL.KetNoiDBDataContext().dmloaithus;

            //translate 
            if (Biencucbo.ngonngu.ToString() == "Vietnam")
            {
                coldiengiai.Summary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridColumnSummaryItem(DevExpress.Data.SummaryItemType.Sum, "diengiai", "Tổng cộng:")});
                gridColumn48.Summary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridColumnSummaryItem(DevExpress.Data.SummaryItemType.Sum, "diengiai", "Tổng cộng:")});

                //gridColumn27.Caption = "Số Hóa đơn";
                //gridColumn28.Caption = "Ngày lập";

                //gridColumn30.Caption = "Đối tượng";
                //gridColumn31.Caption = "Tổng tiền (KIP)";

                gridColumn77.Caption = "Mã Đối Tượng";
                gridColumn78.Caption = "Tên Đối Tượng ";
                gridColumn79.Caption = "Nhóm Đối Tượng";
                gridColumn80.Caption = "Loại Đối Tượng";
                gridColumn81.Caption = "Địa Chỉ";
                gridColumn82.Caption = "Tiền tệ";
                gridColumn83.Caption = "Tỷ giá";
                gridColumn84.Caption = "Ghi chú";
                gridColumn43.Caption = "Mã công việc";
                gridColumn44.Caption = "Tên công việc";
                gridColumn46.Caption = "Nhóm công việc";

                gridColumn41.Caption = "Mục chi phí";
                gridColumn42.Caption = "Tên chi phí";
            }
            else
            {
                coldiengiai.Summary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridColumnSummaryItem(DevExpress.Data.SummaryItemType.Sum, "diengiai", "ລວມທັງໝົດ:")});
                gridColumn48.Summary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridColumnSummaryItem(DevExpress.Data.SummaryItemType.Sum, "diengiai", "ລວມທັງໝົດ:")});
                //gridColumn47.Caption = "ລະຫັດຫົວໜ່ວຍ";
                //gridColumn27.Caption = "ລະຫັດໃບບິນ";
                //gridColumn28.Caption = "ວັນທີ່";
                //gridColumn29.Caption = "ເນື້ອໃນ";
                //gridColumn30.Caption = "ເປົ້າໝາຍ";
                //gridColumn31.Caption = "ລວມເປັນເງິນ (ກີບ)";

                gridColumn77.Caption = "ລະຫັດ";
                gridColumn78.Caption = "ຊື່ເປົ້າໝາຍ";
                gridColumn79.Caption = "ກຸ່ມເປົ້າໝາຍ";
                gridColumn80.Caption = "ປະເພດເປົ້າໝາຍ";
                gridColumn81.Caption = "ທີ່ຢູ່";
                gridColumn82.Caption = "ເງິນຕາ";
                gridColumn83.Caption = "ອັດຕາແລກປ່ຽນ";
                gridColumn84.Caption = "ໝາຍເຫດ";
                gridColumn43.Caption = "ລະຫັດຂອງວຽກງານ";
                gridColumn44.Caption = "ຊື່ວຽກງານ";
                gridColumn46.Caption = "ກຸ່ມໜ້າວຽກ";

                gridColumn41.Caption = "ບັນຊີລາຍຈ່າຍ";
                gridColumn42.Caption = "ຊື່ລາຍຈ່າຍ";
            }
        }
        //load
        public void load()
        {
            db = new KetNoiDBDataContext();
            Biencucbo.hdpt = 2;
            txt1.Enabled = false;

            btnLuu.Enabled = false;
            btnsua.Enabled = true;
            btnxoa.Enabled = true;
            btnin.Enabled = true;
            btnreload.Enabled = false;

            txtdv.ReadOnly = true;
            txtid.ReadOnly = true;
            txtdiachi.ReadOnly = true;
            txtidnv.ReadOnly = true;
            txtphongban.ReadOnly = true;

            // Enable
            txtghichu.ReadOnly = true;
            txtngaynhap.ReadOnly = true;
            txtiddt.ReadOnly = true;
            txtch.ReadOnly = true;

            txttiente.ReadOnly = true;

            txttygia.ReadOnly = true;
            gridView1.OptionsBehavior.Editable = false;

            try
            {
                var lst = (from a in db.pttoans where a.iddv == Biencucbo.donvi select a.so).Max();
                var lst1 = (from b in db.pttoans where b.iddv == Biencucbo.donvi select b).FirstOrDefault(t => t.so == lst);
                if (lst1 == null) return;

                gcchitiet.DataSource = lst1.pttoancts;

                txtid.Text = lst1.id;

                txtidnv.Text = lst1.idnv;
                txtdv.Text = lst1.iddv;
                txtngaynhap.DateTime = DateTime.Parse(lst1.ngaythu.ToString());
                txtiddt.Text = lst1.iddt;
                txttiente.Text = lst1.tiente;
                txttygia.Text = lst1.tygia.ToString();
                txtghichu.Text = lst1.ghichu;


                txt1.Text = lst1.so.ToString();
                txtch.Text = lst1.dv;
                try
                {
                    var lst1a = (from a in db.donvis select a).Single(t => t.id == txtch.Text);
                    lblch.Text = lst1a.tendonvi;
                }
                catch
                {

                }
            }
            catch
            {
            }
        }


        // phân quyền 
        protected override void OnActivated(EventArgs e)
        {
            base.OnActivated(e);
            var q = Biencucbo.QuyenDangChon;
            if (q == null) return;

            if ((bool)q.Them == true)
            {
                btnnew.Visibility = DevExpress.XtraBars.BarItemVisibility.Always;
            }
            else
            {
                btnnew.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            }
            if ((bool)q.Sua == true)
            {
                btnsua.Visibility = DevExpress.XtraBars.BarItemVisibility.Always;
            }
            else
            {
                btnsua.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            }
            if ((bool)q.Xoa == true)
            {
                btnxoa.Visibility = DevExpress.XtraBars.BarItemVisibility.Always;
            }
            else
            {
                btnxoa.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            }
        }
        // Mở
        private void btnmo_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            db = new KetNoiDBDataContext();
            f_dspttoan frm = new f_dspttoan();
            frm.ShowDialog();
            if (Biencucbo.getID == 1)
            {
                //load pnhap
                try
                {
                    var lst = (from pn in db.pttoans select new { a = pn }).FirstOrDefault(x => x.a.id == Biencucbo.ma);

                    if (lst == null) return;

                    txtid.Text = lst.a.id;
                    txtidnv.Text = lst.a.idnv;
                    txtdv.Text = lst.a.iddv;
                    txtngaynhap.DateTime = DateTime.Parse(lst.a.ngaythu.ToString());
                    txtiddt.Text = lst.a.iddt;
                    txtghichu.Text = lst.a.ghichu;
                    txt1.Text = lst.a.so.ToString();
                    txttiente.Text = lst.a.tiente;

                    txttygia.Text = lst.a.tygia.ToString();
                    txtch.Text = lst.a.dv;
                    try
                    {
                        var lst1a = (from a in db.donvis select a).Single(t => t.id == txtch.Text);
                        lblch.Text = lst1a.tendonvi;
                    }
                    catch
                    {

                    }

                    gcchitiet.DataSource = lst.a.pttoancts;

                    //btn
                    btnnew.Enabled = true;
                    btnsua.Enabled = true;
                    btnLuu.Enabled = false;
                    btnmo.Enabled = true;
                    btnxoa.Enabled = true;
                    btnin.Enabled = true;
                    btnreload.Enabled = false;
                }
                catch
                {
                }
            }
        }
        //Thêm
        private void btnnew_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Biencucbo.hdpt = 0;
            txtid.DataBindings.Clear();
            txtid.Text = "YYYYY";

            gcchitiet.DataSource = new DAL.KetNoiDBDataContext().View_pttoans;
            for (int i = 0; i <= gridView1.RowCount - 1; i++)
            {
                gridView1.DeleteRow(i);
            }
            gridView1.AddNewRow();

            txtdv.Text = Biencucbo.donvi;
            txtngaynhap.DateTime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
            txtphongban.Text = Biencucbo.phongban;
            txtidnv.Text = Biencucbo.idnv.Trim();
            lbltennv.Text = Biencucbo.ten;
            txtngaynhap.Focus();
            txtiddt.Text = "";
            lbltendt.Text = "";
            txtch.Text = "";
            lblch.Text = "";
            txtghichu.Text = "";
            txttiente.Text = "KIP";

            txttygia.Text = "1";

            //btn
            btnnew.Enabled = false;
            btnmo.Enabled = false;
            btnLuu.Enabled = true;
            btnsua.Enabled = false;
            btnxoa.Enabled = false;
            btnin.Enabled = false;
            btnreload.Enabled = false;

            //enabled
            txtghichu.ReadOnly = false;
            txtngaynhap.ReadOnly = false;
            txtiddt.ReadOnly = false;
            txtch.ReadOnly = false;

            txttiente.ReadOnly = false;

            txttygia.ReadOnly = true;
            gridView1.OptionsBehavior.Editable = true;
        }

        //Lưu
        public void luu()
        {
            t_history hs = new t_history();
            t_tudong td = new t_tudong();

            gridView1.UpdateCurrentRow();

            if (txtngaynhap.Text == "" || txtiddt.Text == "" || txttiente.Text == "" || txttygia.Text == "" || txtch.Text == "")
            {
                Lotus.MsgBox.ShowWarningDialog("Thông tin chưa đầy đủ - Vui lòng kiểm tra lại!");
                return;
            }
            if (Convert.ToDateTime(txtngaynhap.DateTime.ToShortDateString()) > Convert.ToDateTime(DateTime.Now.ToShortDateString()))
            {
                Lotus.MsgBox.ShowWarningDialog("Ngày nhập không thể lớn hơn Ngày hiện tại! Vui lòng kiểm tra lại!");
                return;
            }
            else
            {
                if (Biencucbo.hdpt == 0)
                {
                    db = new KetNoiDBDataContext();
                    try
                    {
                        string check = "PTTX" + Biencucbo.donvi.Trim().ToString();
                        var lst1 = (from s in db.tudongs where s.maphieu == check select new { so = s.so }).ToList();

                        if (lst1.Count == 0)
                        {
                            int so;

                            so = 2;
                            td.themtudong(check, so);
                            txtid.Text = check + "_000001";
                            txt1.Text = "1";
                        }

                        else
                        {
                            int k;
                            txt1.DataBindings.Clear();
                            txt1.DataBindings.Add("text", lst1, "so");
                            k = 0;
                            k = Convert.ToInt32(txt1.Text);
                            string so0 = "";
                            if (k < 10)
                            {
                                so0 = "00000";
                            }
                            else if (k >= 10 & k < 100)
                            {
                                so0 = "0000";
                            }
                            else if (k >= 100 & k < 1000)
                            {
                                so0 = "000";
                            }
                            else if (k >= 1000 & k < 10000)
                            {
                                so0 = "00";
                            }
                            else if (k >= 10000 & k < 100000)
                            {
                                so0 = "0";
                            }
                            else if (k >= 100000)
                            {
                                so0 = "";
                            }
                            txtid.Text = check + "_" + so0 + k;

                            k = k + 1;

                            td.suatudong(check, k);
                        }
                        pttoan.moipttoan(txtid.Text, txtngaynhap.DateTime, txtiddt.Text, txtdv.Text, txtidnv.Text, txtghichu.Text, Convert.ToInt32(txt1.Text), txtch.Text, txttiente.Text, double.Parse(txttygia.Text));

                        // History
                        //hs.add(txtid.Text, "Thêm mới chứng từ - ເພີ່ມເອກະສານໃໝ່ - ERROR");

                        for (int i = 0; i <= gridView1.RowCount - 1; i++)
                        {
                            gridView1.SetRowCellValue(i, "idttoan", txtid.Text);
                            gridView1.SetRowCellValue(i, "id", txtid.Text + i);

                            pttoan.moict(gridView1.GetRowCellValue(i, "diengiai").ToString(), gridView1.GetRowCellValue(i, "idcv").ToString(), gridView1.GetRowCellValue(i, "idmuccp").ToString(), double.Parse(gridView1.GetRowCellValue(i, "thanhtien").ToString()), gridView1.GetRowCellValue(i, "idttoan").ToString(), gridView1.GetRowCellValue(i, "id").ToString(), double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString())/*, gridView1.GetRowCellValue(i, "tkco").ToString()*/);
                        }

                        // History
                        hs.add(txtid.Text, "Thêm mới chứng từ - ເພີ່ມເອກະສານໃໝ່");

                        //btn
                        btnmo.Enabled = true;
                        btnnew.Enabled = true;
                        btnLuu.Enabled = false;
                        btnsua.Enabled = true;
                        btnxoa.Enabled = true;
                        btnin.Enabled = true;
                        btnreload.Enabled = false;

                        //enabled
                        txtghichu.ReadOnly = true;
                        txtngaynhap.ReadOnly = true;
                        txtiddt.ReadOnly = true;
                        txtch.ReadOnly = true;

                        txttiente.ReadOnly = true;

                        txttygia.ReadOnly = true;
                        gridView1.OptionsBehavior.Editable = false;
                        Biencucbo.hdpt = 2;

                        ShowAlert.Alert_Add_Success(this);
                    }
                    catch (Exception ex)
                    {
                        Lotus.MsgBox.ShowErrorDialog(ex.ToString());
                    }
                }

                else
                {
                    try
                    {
                        pttoan.suapt(txtid.Text, DateTime.Parse(txtngaynhap.Text), txtiddt.Text, txtghichu.Text, int.Parse(txt1.Text), txtch.Text, txttiente.Text, double.Parse(txttygia.Text));
                        //hs.add(txtid.Text, "Sửa chứng từ - ດັດແກ້ເອກະສານ - ERROR");
                        //sua ct
                        LuuPhieu();
                        hs.add(txtid.Text, "Sửa chứng từ - ດັດແກ້ເອກະສານ");

                        //btn
                        btnmo.Enabled = true;
                        btnnew.Enabled = true;
                        btnLuu.Enabled = false;
                        btnsua.Enabled = true;
                        btnxoa.Enabled = true;
                        btnin.Enabled = true;
                        btnreload.Enabled = false;

                        //enabled
                        txtghichu.ReadOnly = true;
                        txtngaynhap.ReadOnly = true;
                        txtiddt.ReadOnly = true;
                        txtch.ReadOnly = true;

                        txttiente.ReadOnly = true;

                        txttygia.ReadOnly = true;
                        gridView1.OptionsBehavior.Editable = false;
                        Biencucbo.hdpt = 2;
                         
                        ShowAlert.Alert_Edit_Success(this);
                    }
                    catch (Exception ex)
                    {
                        Lotus.MsgBox.ShowErrorDialog(ex.ToString());
                    }
                }
            }
        }
        private void btnLuu_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //check khoa so
            if (checkKhoaSo.checkkhoaso(txtdv, txtngaynhap) == false) return;

            gridView1.PostEditor();

            luu();
        }
        bool LuuPhieu()
        {
            // kiem tra truoc khi luu
            layoutControl1.Validate();
            gridView1.CloseEditor();
            gridView1.UpdateCurrentRow();

            // if(kiem tra rang buoc)
            //  return false;

            try
            {

                var c1 = db.pttoans.Context.GetChangeSet();

                /* db.pnhaps.Context.SubmitChanges(); */// dang báo lỗi là vi không có thay đổi. kiem tra neu có thay doi hãy submit

                db.pttoancts.Context.SubmitChanges();

            }

            catch (Exception ex)
            {
                Lotus.MsgBox.ShowErrorDialog(ex.ToString());
                return false;
            }

            return true;
        }
        //Sửa
        private void btnsua_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //check khoa so
            if (checkKhoaSo.checkkhoaso(txtdv, txtngaynhap) == false) return;

            if (txtid.Text == "")
            {

                return;
            }

            //load 
            try
            {
                var lst = (from pn in db.pttoans select pn).FirstOrDefault(x => x.id == txtid.Text);
                if (lst == null) return;

                //enabled
                txtghichu.ReadOnly = false;
                txtngaynhap.ReadOnly = false;
                txtiddt.ReadOnly = false;
                txtch.ReadOnly = false;

                txttiente.ReadOnly = false;

                txttygia.ReadOnly = true;
                gcchitiet.DataSource = lst.pttoancts;
                gridView1.OptionsBehavior.Editable = true;

                Biencucbo.hdpt = 1;

                // btn
                btnsua.Enabled = false;
                btnLuu.Enabled = true;
                btnmo.Enabled = false;
                btnnew.Enabled = false;
                btnxoa.Enabled = false;
                btnin.Enabled = false;
                btnreload.Enabled = true;
            }
            catch
            {
            }
        }
        //Xóa
        private void btnxoa_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //check khoa so
            if (checkKhoaSo.checkkhoaso(txtdv, txtngaynhap) == false) return;

            if (txtid.Text == "")
            {
                return;
            }

            if (XtraMessageBox.Show("Bạn có chắc chắn muốn xóa Phiếu " + txtid.Text + " không?", "THÔNG BÁO", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == System.Windows.Forms.DialogResult.Yes)
            {

                try
                {
                    t_history hs = new t_history();
                    hs.add(txtid.Text, "Xóa chứng từ - ລົບເອກະສານ");

                    for (int i = gridView1.DataRowCount - 1; i >= 0; i--)
                    {
                        pttoan.xoact(gridView1.GetRowCellValue(i, "id").ToString());
                        gridView1.DeleteRow(i);
                    }
                    pttoan.xoapttoan(txtid.Text);

                    //btn
                    btnmo.Enabled = true;
                    btnnew.Enabled = true;
                    btnLuu.Enabled = false;
                    btnsua.Enabled = true;
                    btnxoa.Enabled = true;
                    btnin.Enabled = true;
                    btnreload.Enabled = false;


                    //enabled
                    txtghichu.ReadOnly = true;
                    txtngaynhap.ReadOnly = true;
                    txtiddt.ReadOnly = true;
                    txtch.ReadOnly = true;

                    txttiente.ReadOnly = true;

                    txttygia.ReadOnly = true;
                    gridView1.OptionsBehavior.Editable = false;

                    //gcchitiet.DataSource = new DAL.KetNoiDBDataContext().View_pnhapcts;
                    txtdv.Text = "";
                    txtid.Text = "";
                    txtidnv.Text = "";
                    txtdv.Text = "";
                    txtngaynhap.Text = "";
                    txtiddt.Text = "";
                    txtghichu.Text = "";
                    txt1.Text = "";
                    txtch.Text = "";
                    lblch.Text = "";
                    lbltendt.Text = "";
                    lbltennv.Text = "";
                    txttiente.Text = "";

                    txttygia.Text = "";

                    ShowAlert.Alert_Del_Success(this);

                }

                catch
                {
                }

            }
        }

        //reload
        private void btnload_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (Biencucbo.hdpt == 1)
            {
                db = new KetNoiDBDataContext();

                var lst = (from pn in db.pttoans select pn).FirstOrDefault(x => x.id == txtid.Text);

                if (lst == null) return;

                txtidnv.Text = lst.idnv;
                txtdv.Text = lst.iddv;
                txtngaynhap.DateTime = DateTime.Parse(lst.ngaythu.ToString());
                txtiddt.Text = lst.iddt;
                txtghichu.Text = lst.ghichu;
                txt1.Text = lst.so.ToString();
                txtch.Text = lst.dv;
                try
                {
                    var lst1a = (from a in db.donvis select a).Single(t => t.id == txtch.Text);
                    lblch.Text = lst1a.tendonvi;
                }
                catch
                {

                }

                txttiente.Text = lst.tiente;

                txttygia.Text = lst.tygia.ToString();
                gcchitiet.DataSource = lst.pttoancts;


                //readonly
                txtghichu.ReadOnly = true;
                txtngaynhap.ReadOnly = true;
                txttiente.ReadOnly = true;

                txttygia.ReadOnly = true;
                txtiddt.ReadOnly = true;
                txtch.ReadOnly = true;



                //btn
                btnnew.Enabled = true;
                btnsua.Enabled = true;
                btnLuu.Enabled = false;
                btnmo.Enabled = true;
                btnxoa.Enabled = true;
                btnin.Enabled = true;
                btnreload.Enabled = false;
                gridView1.OptionsBehavior.Editable = false;
            }

            else if (Biencucbo.hdpt == 0)
            {
                load();
                btnnew.Enabled = true;
                btnsua.Enabled = true;
                btnLuu.Enabled = false;
                btnmo.Enabled = true;
                btnxoa.Enabled = true;
                btnin.Enabled = true;
                btnreload.Enabled = false;
                gridView1.OptionsBehavior.Editable = false;
            }
            Biencucbo.hdpt = 2;
        }

        // thay đổi
        private void gridView1_CellValueChanged(object sender, DevExpress.XtraGrid.Views.Base.CellValueChangedEventArgs e)
        {
            gridView1.PostEditor();
            if (e.Column.FieldName == "nguyente")
            {
                try
                {
                    gridView1.SetFocusedRowCellValue("thanhtien", (double.Parse(gridView1.GetFocusedRowCellValue("nguyente").ToString())) * (double.Parse(txttygia.Text)));
                }
                catch (Exception)
                {
                }
            }
        }

        //Phím Tắt
        private void gridView1_KeyDown(object sender, KeyEventArgs e)
        {
            if (Biencucbo.hdpt == 2)
                return;
            if (e.KeyCode == Keys.Insert)
            {
                gridView1.AddNewRow();

            }
            else if (e.KeyCode == Keys.Delete)
            {
                if (Biencucbo.hdpt == 1)
                {
                    try
                    {
                        pttoanct ct = (from c in db.pttoancts select c).Single(x => x.id == gridView1.GetFocusedRowCellValue("id").ToString());
                        db.pttoancts.DeleteOnSubmit(ct);
                    }
                    catch
                    {
                    }
                }

                gridView1.DeleteRow(gridView1.FocusedRowHandle);
            }
        }
        //đối tượng
        private void txtiddt_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                var lst = (from a in db.doituongs select a).Single(t => t.id == txtiddt.Text);
                lbltendt.Text = lst.ten.ToString();
                txtdiachi.Text = lst.diachi.ToString();
            }
            catch (Exception)
            {
            }
        }


        //Dòng mới
        private void gridView1_InitNewRow(object sender, InitNewRowEventArgs e)
        {
            if (Biencucbo.hdpt == 1)
            {
                var ct = gridView1.GetFocusedRow() as pttoanct;
                if (ct == null) return;

                int i = 0, k = 0;
                string a;

                k = gridView1.DataRowCount;
                a = txtid.Text + k;

                for (i = 0; i <= gridView1.DataRowCount - 1;)
                {
                    if (a == gridView1.GetRowCellValue(i, "id").ToString())
                    {
                        k = k + 1;
                        a = txtid.Text + k;
                        i = 0;
                    }
                    else
                    {
                        i++;
                    }
                }

                ct.idttoan = txtid.Text;

                ct.diengiai = "";
                ct.idmuccp = "";
                ct.idcv = "";
                ct.thanhtien = 0;
                ct.id = a;
                ct.nguyente = 0;
            }

            else
            {
                gridView1.SetFocusedRowCellValue("diengiai", "");
                gridView1.SetFocusedRowCellValue("tygia", 1);
                gridView1.SetFocusedRowCellValue("idmuccp", "");
                gridView1.SetFocusedRowCellValue("tiente", "KIP");
                gridView1.SetFocusedRowCellValue("idcv", "");
                gridView1.SetFocusedRowCellValue("nguyente", 0);
            }
        }
        //Xóa dòng

        private void btnin_ItemClick_1(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                //var lst = (from a in db.r_pttoans where a.id == txtid.Text select a);
                //r_pttoan xtra = new r_pttoan();
                //xtra.DataSource = lst;
                //xtra.ShowPreviewDialog();
            }
            catch
            {
            }
        }

        //đóng form
        private void f_pnhap_FormClosing(object sender, FormClosingEventArgs e)
        {
            if (Biencucbo.hdpt != 2)
            {
                var a = Lotus.MsgBox.ShowYesNoCancelDialog("Phiếu này chưa được lưu - Bạn có muốn lưu Phiếu này trước khi thoát không?");
                if (a == DialogResult.Yes)
                {
                    luu();
                }
                else if (a == DialogResult.Cancel) e.Cancel = true;
            }
        }

        private void gridView1_CustomDrawRowIndicator(object sender, RowIndicatorCustomDrawEventArgs e)
        {
            if (!gridView1.IsGroupRow(e.RowHandle)) //Nếu không phải là Group
            {
                if (e.Info.IsRowIndicator) //Nếu là dòng Indicator
                {
                    if (e.RowHandle < 0)
                    {
                        e.Info.ImageIndex = 0;
                        e.Info.DisplayText = string.Empty;
                    }
                    else
                    {
                        e.Info.ImageIndex = -1; //Không hiển thị hình
                        e.Info.DisplayText = (e.RowHandle + 1).ToString(); //Số thứ tự tăng dần
                    }
                    SizeF _Size = e.Graphics.MeasureString(e.Info.DisplayText, e.Appearance.Font); //Lấy kích thước của vùng hiển thị Text
                    Int32 _Width = Convert.ToInt32(_Size.Width) + 20;
                    BeginInvoke(new MethodInvoker(delegate { cal(_Width, gridView1); })); //Tăng kích thước nếu Text vượt quá
                }
            }
            else
            {
                e.Info.ImageIndex = -1;
                e.Info.DisplayText = string.Format("[{0}]", (e.RowHandle * -1)); //Nhân -1 để đánh lại số thứ tự tăng dần
                SizeF _Size = e.Graphics.MeasureString(e.Info.DisplayText, e.Appearance.Font);
                Int32 _Width = Convert.ToInt32(_Size.Width) + 20;
                BeginInvoke(new MethodInvoker(delegate { cal(_Width, gridView1); }));
            }
        }
        bool cal(Int32 _Width, GridView _View)
        {
            _View.IndicatorWidth = _View.IndicatorWidth < _Width ? _Width : _View.IndicatorWidth;
            return true;
        }

        private void btnmuccp_EditValueChanged(object sender, EventArgs e)
        {
            gridView1.PostEditor();
        }

        private void rsearchtiente1_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                gridView1.PostEditor();
                var lst = (from a in db.tientes select a).Single(t => t.tiente1 == gridView1.GetFocusedRowCellValue("tiente").ToString());
                if (lst == null) return;
                gridView1.SetFocusedRowCellValue("tygia", lst.tygia);
                gridView1.SetFocusedRowCellValue("thanhtien", int.Parse(gridView1.GetFocusedRowCellValue("nguyente").ToString()) * int.Parse(gridView1.GetFocusedRowCellValue("tygia").ToString()));
            }
            catch
            {
            }
        }



        private void txttiente_EditValueChanged(object sender, EventArgs e)
        {
            if (txttiente.Text != "")
            {
                var lst = (from a in db.tientes select a).FirstOrDefault(t => t.tiente1 == txttiente.Text);
                txttygia.Text = lst.tygia.ToString();


                for (int i = 0; i <= gridView1.RowCount - 1; i++)
                {
                    try
                    {
                        gridView1.SetRowCellValue(i, "thanhtien", double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()) * double.Parse(txttygia.Text));
                    }
                    catch
                    {
                    }
                }
            }
        }

        private void btnPrev_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (txtngaynhap.Text == "") return;
            else
            {
                try
                {
                    var lst = (from pn in db.pttoans select new { a = pn }).FirstOrDefault(x => x.a.iddv == Biencucbo.donvi && x.a.ngaythu == (txtngaynhap.DateTime.AddDays(-1)));
                    if (lst == null)
                    {
                        lst = (from pn in db.pttoans select new { a = pn }).OrderByDescending(x => x.a.ngaythu).FirstOrDefault(x => x.a.iddv == Biencucbo.donvi && x.a.ngaythu < txtngaynhap.DateTime);
                    }
                    txtid.Text = lst.a.id;
                    txtidnv.Text = lst.a.idnv;
                    txtdv.Text = lst.a.iddv;
                    txtngaynhap.DateTime = DateTime.Parse(lst.a.ngaythu.ToString());
                    txtiddt.Text = lst.a.iddt;
                    txtghichu.Text = lst.a.ghichu;
                    txt1.Text = lst.a.so.ToString();
                    txttiente.Text = lst.a.tiente;

                    txttygia.Text = lst.a.tygia.ToString();
                    txtch.Text = lst.a.dv;

                    try
                    {
                        var lst1a = (from a in db.donvis select a).Single(t => t.id == txtch.Text);
                        lblch.Text = lst1a.tendonvi;
                    }
                    catch
                    {

                    }
                    gcchitiet.DataSource = lst.a.pttoancts;
                }
                catch
                {
                }
            }
        }

        private void btnNext_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (txtngaynhap.Text == "") return;
            else
            {
                try
                {
                    var lst = (from pn in db.pttoans select new { a = pn }).FirstOrDefault(x => x.a.iddv == Biencucbo.donvi && x.a.ngaythu == (txtngaynhap.DateTime.AddDays(1)));
                    if (lst == null)
                    {
                        lst = (from pn in db.pttoans select new { a = pn }).OrderBy(x => x.a.ngaythu).FirstOrDefault(x => x.a.iddv == Biencucbo.donvi && x.a.ngaythu > txtngaynhap.DateTime);
                    }
                    txtid.Text = lst.a.id;
                    txtidnv.Text = lst.a.idnv;
                    txtdv.Text = lst.a.iddv;
                    txtngaynhap.DateTime = DateTime.Parse(lst.a.ngaythu.ToString());
                    txtiddt.Text = lst.a.iddt;
                    txtghichu.Text = lst.a.ghichu;
                    txt1.Text = lst.a.so.ToString();
                    txttiente.Text = lst.a.tiente;

                    txttygia.Text = lst.a.tygia.ToString();
                    txtch.Text = lst.a.dv;

                    try
                    {
                        var lst1a = (from a in db.donvis select a).Single(t => t.id == txtch.Text);
                        lblch.Text = lst1a.tendonvi;
                    }
                    catch
                    {

                    }
                    gcchitiet.DataSource = lst.a.pttoancts;
                }
                catch
                {
                }
            }
        }

        private void f_pttoan_Load(object sender, EventArgs e)
        {
            LanguageHelper.Translate(this);
            LanguageHelper.Translate(barManager1);
            this.Text = LanguageHelper.TranslateMsgString("." + Name + "_title", "Phiếu Thu Tiền Từ Xa").ToString();

            changeFont.Translate(this);
            changeFont.Translate(barManager1);

            load();
        }

        private void txtch_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                var lst1a = (from a in db.donvis select a).Single(t => t.id == txtch.Text);
                lblch.Text = lst1a.tendonvi;
            }
            catch
            {

            }
        }

        private void txtidnv_EditValueChanged(object sender, EventArgs e)
        {

        }
    }
}