using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DAL;
using BUS;
using DevExpress.Utils.Win;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid;
using System.Data.Linq;
using DevExpress.XtraReports.UI;
using ControlLocalizer;
using GUI.Libs;

namespace GUI
{
    public partial class f_pthu_tt : Form
    {
        KetNoiDBDataContext db = new KetNoiDBDataContext();
        t_pthu pthu = new t_pthu();

        //form
        public f_pthu_tt()
        {
            InitializeComponent();
            lblbo.Text = "";

            rsearchtiente1.DataSource = new DAL.KetNoiDBDataContext().tientes;
            txttiente.Properties.DataSource = new DAL.KetNoiDBDataContext().tientes;


            btnmuccp.DataSource = new DAL.KetNoiDBDataContext().muccps;
            btncongviec1.DataSource = new DAL.KetNoiDBDataContext().congviecs;
            txtiddt.Properties.DataSource = new DAL.KetNoiDBDataContext().doituongs;
            try
            {
                var lst = from a in db.hoadons
                          join b in db.hoadoncts on a.id equals b.idhoadon into g
                          join c in db.doituongs on a.iddt equals c.id
                          join d in db.donvis on a.iddv equals d.id
                          where Biencucbo.donvi == a.iddv || Biencucbo.donvi == d.iddv
                          select new
                          {
                              mahd = a.id,
                              ngayhd = a.ngayhd,
                              noidung = a.ghichu,
                              doituong = c.ten,
                              iddv = a.iddv,
                              tongtien = g.Sum(t => t.thanhtien)
                          };
                txtsohd.Properties.DataSource = lst;
            }
            catch
            {
            }

            // This line of code is generated by Data Source Configuration Wizard
            txtloaithu.Properties.DataSource = new DAL.KetNoiDBDataContext().dmloaithus;

            if (Biencucbo.ngonngu.ToString() == "Vietnam")
            {
                coldiengiai.Summary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridColumnSummaryItem(DevExpress.Data.SummaryItemType.Sum, "diengiai", "Tổng cộng:")});
                gridColumn48.Summary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridColumnSummaryItem(DevExpress.Data.SummaryItemType.Sum, "diengiai", "Tổng cộng:")});
            }
            else
            {
                coldiengiai.Summary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridColumnSummaryItem(DevExpress.Data.SummaryItemType.Sum, "diengiai", "ລວມທັງໝົດ:")});
                gridColumn48.Summary.AddRange(new DevExpress.XtraGrid.GridSummaryItem[] {
            new DevExpress.XtraGrid.GridColumnSummaryItem(DevExpress.Data.SummaryItemType.Sum, "diengiai", "ລວມທັງໝົດ:")});
            }
        }

        //load
        public void load()
        {
            // Lấy dữ liệu form hóa đơn
            var check = (from a in db.pthus where a.link == Biencucbo.thanhtoan select a);
            if (check.Count() == 0)
            {
                Biencucbo.hdpt = 0;
                btnload.Enabled = false;
                txt1.Enabled = false;
                db = new KetNoiDBDataContext();

                var lst = (from a in db.hoadons

                           join b in db.hoadoncts on a.id equals b.idhoadon into g
                           join c in db.doituongs on a.iddt equals c.id
                           join d in db.donvis on a.iddv equals d.id

                           where a.id == Biencucbo.thanhtoan
                           select new
                           {
                               mahd = a.id,
                               ngayhd = a.ngayhd,
                               noidung = a.ghichu,
                               doituong = c.ten,
                               iddt = a.iddt,
                               iddv = a.iddv,
                               tiente = a.tiente,
                               tygia = a.tygia,
                               tongtien = g.Sum(t => t.thanhtien)
                           }).Single();


                gcchitiet.DataSource = new DAL.KetNoiDBDataContext().View_pthus;
                for (int i = 0; i <= gridView1.RowCount - 1; i++)
                {
                    gridView1.DeleteRow(i);
                }
                gridView1.AddNewRow();
                this.Refresh();

                // truyền thông tin
                txtiddt.Text = lst.iddt.ToString();
                txtsohd.Text = lst.iddt.ToString();
                txtghichu.Text = "Thu tiền bán hàng";
                txtloaithu.Text = "Thu tiền bán hàng - ຮັບເງິນຂາຍສິນຄ້າ";
                txtsohd.Text = Biencucbo.thanhtoan;
                gridView1.SetFocusedRowCellValue("nguyente", double.Parse(lst.tongtien.ToString()));
                gridView1.SetFocusedRowCellValue("thanhtien", double.Parse(lst.tongtien.ToString()) * double.Parse(lst.tygia.ToString()));
                gridView1.SetFocusedRowCellValue("diengiai", "");
                gridView1.SetFocusedRowCellValue("idcv", "");
                gridView1.SetFocusedRowCellValue("idmuccp", "");
                gridView1.SetFocusedRowCellValue("tygia", "1");
                gridView1.SetFocusedRowCellValue("tiente", "KIP");

                gridView1.OptionsBehavior.Editable = true;
                txttiente.Text = lst.tiente;
                txttygia.Text = lst.tygia.ToString();


                txtdv.ReadOnly = true;
                txtid.ReadOnly = true;
                txtdiachi.ReadOnly = true;
                txtidnv.ReadOnly = true;
                txtphongban.ReadOnly = true;

                txtdv.Text = Biencucbo.donvi;
                txtngaynhap.DateTime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
                txtphongban.Text = Biencucbo.phongban;
                txtidnv.Text = Biencucbo.idnv.Trim();
                lbltennv.Text = Biencucbo.ten;
                txtngaynhap.Focus();

                txtid.DataBindings.Clear();
                txtid.Text = "YYYYY";
                this.Refresh();

                //btn 
                btnmo.Enabled = false;
                btnLuu.Enabled = true;
                btnsua.Enabled = false;
                btnxoa.Enabled = false;
                btnin.Enabled = false;
                btnreload.Enabled = false;

                //enabled
                txtghichu.ReadOnly = false;
                txtngaynhap.ReadOnly = false;
                txtiddt.ReadOnly = false;
                txtsohd.ReadOnly = false;
                gcchitiet.Enabled = true;
                txtsohd.ReadOnly = true;
                txtloaithu.ReadOnly = true;

                txttiente.ReadOnly = true;
                txttk.ReadOnly = true;
                txttygia.ReadOnly = true;
            }

            else
            {
                Biencucbo.hdpt = 2;
                txt1.Enabled = false;

                btnnew.Enabled = false;
                btnthemmoi.Enabled = false;
                btnLuu.Enabled = false;
                btnsua.Enabled = true;
                btnxoa.Enabled = true;
                btnin.Enabled = true;
                btnreload.Enabled = false;

                txtdv.ReadOnly = true;
                txtid.ReadOnly = true;
                txtdiachi.ReadOnly = true;
                txtidnv.ReadOnly = true;
                txtphongban.ReadOnly = true;
                txttiente.ReadOnly = true;
                txttk.ReadOnly = true;
                txttygia.ReadOnly = true;

                // Enable
                txtghichu.ReadOnly = true;
                txtngaynhap.ReadOnly = true;
                txtiddt.ReadOnly = false;
                txtsohd.ReadOnly = true;
                txtloaithu.ReadOnly = true;
                gridView1.OptionsBehavior.Editable = false;

                try
                {
                    var check2 = (from a in db.pthus select a).FirstOrDefault(t => t.link == Biencucbo.thanhtoan);
                    if (check2 == null) return;

                    gcchitiet.DataSource = check2.pthucts;

                    txtid.Text = check2.id;

                    txtidnv.Text = check2.idnv;
                    txtdv.Text = check2.iddv;
                    txtngaynhap.DateTime = DateTime.Parse(check2.ngaythu.ToString());
                    txtiddt.Text = check2.iddt;
                    txtghichu.Text = check2.ghichu;

                    txt1.Text = check2.so.ToString();
                    txtsohd.Text = check2.link;
                    txtloaithu.Text = check2.loaithu;
                    txttiente.Text = check2.tiente;
                    txttygia.Text = check2.tygia.ToString();
                }
                catch
                {
                }
            }
        }

        // phân quyền 
        protected override void OnActivated(EventArgs e)
        {
            base.OnActivated(e);
            var q = Biencucbo.QuyenDangChon;
            if (q == null) return;

            if ((bool)q.Them == true)
            {
                btnnew.Visibility = DevExpress.XtraBars.BarItemVisibility.Always;
            }
            else
            {
                btnnew.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            }
            if ((bool)q.Sua == true)
            {
                btnsua.Visibility = DevExpress.XtraBars.BarItemVisibility.Always;
            }
            else
            {
                btnsua.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            }
            if ((bool)q.Xoa == true)
            {
                btnxoa.Visibility = DevExpress.XtraBars.BarItemVisibility.Always;
            }
            else
            {
                btnxoa.Visibility = DevExpress.XtraBars.BarItemVisibility.Never;
            }
        }

        // Mở
        private void btnmo_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

            db = new KetNoiDBDataContext();
            f_dspthu frm = new f_dspthu();
            frm.ShowDialog();

            if (Biencucbo.getID == 1)
            {
                //load pnhap
                try
                {
                    var lst = (from pn in db.pthus select new { a = pn }).FirstOrDefault(x => x.a.id == Biencucbo.ma);

                    if (lst == null) return;

                    txtid.Text = lst.a.id;
                    txtidnv.Text = lst.a.idnv;
                    txtdv.Text = lst.a.iddv;
                    txtngaynhap.DateTime = DateTime.Parse(lst.a.ngaythu.ToString());
                    txtiddt.Text = lst.a.iddt;
                    txtghichu.Text = lst.a.ghichu;
                    txt1.Text = lst.a.so.ToString();

                    txttiente.Text = lst.a.tiente;
                    txtloaithu.Text = lst.a.loaithu;
                    txttygia.Text = lst.a.tygia.ToString();
                    txtsohd.Text = lst.a.link;
                    gcchitiet.DataSource = lst.a.pthucts;

                    //btn
                    btnnew.Enabled = true;
                    btnsua.Enabled = true;
                    btnLuu.Enabled = false;
                    btnmo.Enabled = true;
                    btnxoa.Enabled = true;
                    btnin.Enabled = true;
                    btnreload.Enabled = false;
                }
                catch
                {
                }
            }
        }
        //Thêm
        private void btnnew_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Biencucbo.hdpt = 0;
            txtid.DataBindings.Clear();
            txtid.Text = "YYYYY";

            gcchitiet.DataSource = new DAL.KetNoiDBDataContext().View_pthus;
            for (int i = 0; i <= gridView1.RowCount - 1; i++)
            {
                gridView1.DeleteRow(i);
            }
            gridView1.AddNewRow();

            txtdv.Text = Biencucbo.donvi;
            txtngaynhap.DateTime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
            txtphongban.Text = Biencucbo.phongban;
            txtidnv.Text = Biencucbo.idnv.Trim();
            lbltennv.Text = Biencucbo.ten;
            txtngaynhap.Focus();
            txtiddt.Text = "";
            lbltendt.Text = "";
            txtsohd.Text = "";
            txtghichu.Text = "";
            txttk.Text = "";
            txttiente.Text = "KIP";
            txttygia.Text = "1";

            //btn
            btnnew.Enabled = false;
            btnmo.Enabled = false;
            btnLuu.Enabled = true;
            btnsua.Enabled = false;
            btnxoa.Enabled = false;
            btnin.Enabled = false;
            btnreload.Enabled = false;

            //enabled
            txtghichu.ReadOnly = false;
            txtngaynhap.ReadOnly = false;
            txtiddt.ReadOnly = false;
            txtsohd.ReadOnly = false;
            txtloaithu.ReadOnly = false;
            txttiente.ReadOnly = false;
            txttk.ReadOnly = true;
            txttygia.ReadOnly = true;
            gridView1.OptionsBehavior.Editable = true;
        }

        //Lưu
        public void luu()
        {
            t_history hs = new t_history();
            t_tudong td = new t_tudong();

            gridView1.UpdateCurrentRow();

            if (txtngaynhap.Text == "" || txtiddt.Text == "" || txttiente.Text == "" || txttygia.Text == "" || txtloaithu.Text == "")
            {
                Lotus.MsgBox.ShowWarningDialog("Thông tin chưa đầy đủ - Vui lòng kiểm tra lại!");
                return;
            }
            if (Convert.ToDateTime(txtngaynhap.DateTime.ToShortDateString()) > Convert.ToDateTime(DateTime.Now.ToShortDateString()))
            {
                Lotus.MsgBox.ShowWarningDialog("Ngày nhập không thể lớn hơn Ngày hiện tại! Vui lòng kiểm tra lại!");
                return;
            }
            else
            {
                if (Biencucbo.hdpt == 0)
                {
                    db = new KetNoiDBDataContext();
                    try
                    {
                        string check = "PT" + Biencucbo.donvi.Trim().ToString();
                        var lst1 = (from s in db.tudongs where s.maphieu == check select new { so = s.so }).ToList();

                        if (lst1.Count == 0)
                        {
                            int so;

                            so = 2;
                            td.themtudong(check, so);
                            txtid.Text = check + "_000001";
                            txt1.Text = "1";
                        }
                        else
                        {

                            int k;
                            txt1.DataBindings.Clear();
                            txt1.DataBindings.Add("text", lst1, "so");
                            k = 0;
                            k = Convert.ToInt32(txt1.Text);
                            string so0 = "";
                            if (k < 10)
                            {
                                so0 = "00000";
                            }
                            else if (k >= 10 & k < 100)
                            {
                                so0 = "0000";
                            }
                            else if (k >= 100 & k < 1000)
                            {
                                so0 = "000";
                            }
                            else if (k >= 1000 & k < 10000)
                            {
                                so0 = "00";
                            }
                            else if (k >= 10000 & k < 100000)
                            {
                                so0 = "0";
                            }
                            else if (k >= 100000)
                            {
                                so0 = "";
                            }
                            txtid.Text = check + "_" + so0 + k;

                            k = k + 1;

                            td.suatudong(check, k);
                        }
                        pthu.moipthu(txtid.Text, txtngaynhap.DateTime, txtiddt.Text, txtdv.Text, txtidnv.Text, txtghichu.Text, Convert.ToInt32(txt1.Text), txtsohd.Text, txttiente.Text, double.Parse(txttygia.Text), txtloaithu.Text);
                        // History 
                        //hs.add(txtid.Text, "Thêm mới chứng từ - ເພີ່ມເອກະສານໃໝ່ - ERROR");

                        for (int i = 0; i <= gridView1.RowCount - 1; i++)
                        {
                            gridView1.SetRowCellValue(i, "idthu", txtid.Text);
                            gridView1.SetRowCellValue(i, "id", txtid.Text + i);
                            //gridView1.SetRowCellValue(i, "tkco", "");

                            pthu.moict(gridView1.GetRowCellValue(i, "diengiai").ToString(), gridView1.GetRowCellValue(i, "idcv").ToString(), gridView1.GetRowCellValue(i, "idmuccp").ToString(), double.Parse(gridView1.GetRowCellValue(i, "thanhtien").ToString()), gridView1.GetRowCellValue(i, "idthu").ToString(), gridView1.GetRowCellValue(i, "id").ToString(), gridView1.GetRowCellValue(i, "tiente").ToString(), double.Parse(gridView1.GetRowCellValue(i, "tygia").ToString()), double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString())/*, gridView1.GetRowCellValue(i, "tkco").ToString()*/);
                        }
                        // History 
                        hs.add(txtid.Text, "Thêm mới chứng từ - ເພີ່ມເອກະສານໃໝ່");

                        //btn
                        btnmo.Enabled = true;
                        btnnew.Enabled = true;
                        btnLuu.Enabled = false;
                        btnsua.Enabled = true;
                        btnxoa.Enabled = true;
                        btnin.Enabled = true;
                        btnreload.Enabled = false;

                        //enabled
                        txtghichu.ReadOnly = true;
                        txtngaynhap.ReadOnly = true;
                        txtiddt.ReadOnly = false;
                        txtsohd.ReadOnly = true;
                        txtloaithu.ReadOnly = true;
                        txttiente.ReadOnly = true;
                        txttk.ReadOnly = true;
                        txttygia.ReadOnly = true;
                        gridView1.OptionsBehavior.Editable = false;
                        Biencucbo.hdpt = 2;
                         
                        ShowAlert.Alert_Add_Success(this);
                    }
                    catch (Exception ex)
                    {
                        Lotus.MsgBox.ShowErrorDialog(ex.ToString());
                    }
                }

                else
                {
                    try
                    {
                        pthu.suapt(txtid.Text, DateTime.Parse(txtngaynhap.Text), txtiddt.Text, txtghichu.Text, int.Parse(txt1.Text), txtsohd.Text, txttiente.Text, double.Parse(txttygia.Text), txtloaithu.Text);

                        //hs.add(txtid.Text, "Sửa chứng từ - ດັດແກ້ເອກະສານ - ERROR");

                        //sua ct
                        LuuPhieu();
                        hs.add(txtid.Text, "Sửa chứng từ - ດັດແກ້ເອກະສານ");

                        //btn
                        btnmo.Enabled = true;
                        btnnew.Enabled = true;
                        btnLuu.Enabled = false;
                        btnsua.Enabled = true;
                        btnxoa.Enabled = true;
                        btnin.Enabled = true;
                        btnreload.Enabled = false;

                        //enabled
                        txtghichu.ReadOnly = true;
                        txtngaynhap.ReadOnly = true;
                        txtiddt.ReadOnly = false;
                        txtsohd.ReadOnly = true;
                        txtloaithu.ReadOnly = true;
                        txttiente.ReadOnly = true;
                        txttk.ReadOnly = true;
                        txttygia.ReadOnly = true;
                        gridView1.OptionsBehavior.Editable = false;
                        Biencucbo.hdpt = 2;

                        ShowAlert.Alert_Edit_Success(this);
                    }
                    catch (Exception ex)
                    {
                        Lotus.MsgBox.ShowErrorDialog(ex.ToString());
                    }
                }
            }
        }
        private void btnLuu_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //check khoa so
            if (checkKhoaSo.checkkhoaso(txtdv, txtngaynhap) == false) return;

            gridView1.PostEditor();
            luu();
        }
        bool LuuPhieu()
        {
            // kiem tra truoc khi luu
            layoutControl1.Validate();
            gridView1.CloseEditor();
            gridView1.UpdateCurrentRow();

            // if(kiem tra rang buoc)
            //  return false;

            try
            {
                var c1 = db.pthus.Context.GetChangeSet();
                db.pthucts.Context.SubmitChanges();
            }
            catch (Exception ex)
            {
                Lotus.MsgBox.ShowErrorDialog(ex.ToString());
                return false;
            }

            return true;
        }
        //Sửa
        private void btnsua_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //check khoa so
            if (checkKhoaSo.checkkhoaso(txtdv, txtngaynhap) == false) return;

            if (txtid.Text == "")
            {
                return;
            }

            //load 
            try
            {
                var lst = (from pn in db.pthus select pn).FirstOrDefault(x => x.id == txtid.Text);
                if (lst == null) return;
                gcchitiet.DataSource = lst.pthucts;
                //enabled
                txtghichu.ReadOnly = false;
                txtngaynhap.ReadOnly = false;
                txtiddt.ReadOnly = false;
                txtsohd.ReadOnly = false;
                txtloaithu.ReadOnly = false;
                txttiente.ReadOnly = false;
                txttk.ReadOnly = true;
                txttygia.ReadOnly = true;
                gridView1.OptionsBehavior.Editable = true;

                Biencucbo.hdpt = 1;

                // btn
                btnsua.Enabled = false;
                btnLuu.Enabled = true;
                btnmo.Enabled = false;
                btnnew.Enabled = false;
                btnxoa.Enabled = false;
                btnin.Enabled = false;
                btnreload.Enabled = true;
            }
            catch
            {
            }
        }
        //Xóa
        private void btnxoa_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //check khoa so
            if (checkKhoaSo.checkkhoaso(txtdv, txtngaynhap) == false) return;

            if (txtid.Text == "")
            {
                return;
            }
            if (XtraMessageBox.Show("Bạn có chắc chắn muốn xóa Phiếu " + txtid.Text + " không?", "THÔNG BÁO", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == System.Windows.Forms.DialogResult.Yes)
            {


                try
                {
                    t_history hs = new t_history();
                    hs.add(txtid.Text, "Xóa chứng từ - ລົບເອກະສານ");

                    for (int i = gridView1.DataRowCount - 1; i >= 0; i--)
                    {
                        pthu.xoact(gridView1.GetRowCellValue(i, "id").ToString());
                        gridView1.DeleteRow(i);
                    }
                    pthu.xoapthu(txtid.Text);

                    //btn
                    btnmo.Enabled = true;
                    btnnew.Enabled = true;
                    btnLuu.Enabled = false;
                    btnsua.Enabled = true;
                    btnxoa.Enabled = true;
                    btnin.Enabled = true;
                    btnreload.Enabled = false;

                    //enabled
                    txtghichu.ReadOnly = true;
                    txtngaynhap.ReadOnly = true;
                    txtiddt.ReadOnly = false;
                    txtsohd.ReadOnly = true;
                    txtloaithu.ReadOnly = true;
                    txttiente.ReadOnly = true;
                    txttk.ReadOnly = true;
                    txttygia.ReadOnly = true;
                    gridView1.OptionsBehavior.Editable = false;

                    //gcchitiet.DataSource = new DAL.KetNoiDBDataContext().View_pnhapcts;
                    txtdv.Text = "";
                    txtid.Text = "";
                    txtidnv.Text = "";
                    txtdv.Text = "";
                    txtngaynhap.Text = "";
                    txtiddt.Text = "";
                    txtghichu.Text = "";
                    txt1.Text = "";
                    txtsohd.Text = "";
                    lbltendt.Text = "";
                    lbltennv.Text = "";
                    txttiente.Text = "";
                    txttk.Text = "";
                    txttygia.Text = "";

                    ShowAlert.Alert_Del_Success(this);
                }
                catch
                {
                }

            }
        }

        //reload
        private void btnload_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (Biencucbo.hdpt == 1)
            {
                db = new KetNoiDBDataContext();

                var lst = (from pn in db.pthus select pn).FirstOrDefault(x => x.id == txtid.Text);

                if (lst == null) return;

                txtidnv.Text = lst.idnv;
                txtdv.Text = lst.iddv;
                txtngaynhap.DateTime = DateTime.Parse(lst.ngaythu.ToString());
                txtiddt.Text = lst.iddt;
                txtghichu.Text = lst.ghichu;
                txt1.Text = lst.so.ToString();
                txtsohd.Text = lst.link;

                txttiente.Text = lst.tiente;
                txttygia.Text = lst.tygia.ToString();
                txtloaithu.Text = lst.loaithu;
                gcchitiet.DataSource = lst.pthucts;

                //readonly
                txtghichu.ReadOnly = true;
                txtngaynhap.ReadOnly = true;
                txttiente.ReadOnly = true;
                txttk.ReadOnly = true;
                txttygia.ReadOnly = true;
                txtiddt.ReadOnly = false;
                txtsohd.ReadOnly = true;
                txtloaithu.ReadOnly = true;

                //btn
                btnnew.Enabled = true;
                btnsua.Enabled = true;
                btnLuu.Enabled = false;
                btnmo.Enabled = true;
                btnxoa.Enabled = true;
                btnin.Enabled = true;
                btnreload.Enabled = false;
                gridView1.OptionsBehavior.Editable = false;
            }

            else if (Biencucbo.hdpt == 0)
            {
                load();
                //btn
                btnnew.Enabled = true;
                btnsua.Enabled = true;
                btnLuu.Enabled = false;
                btnmo.Enabled = true;
                btnxoa.Enabled = true;
                btnin.Enabled = true;
                btnreload.Enabled = false;
                gridView1.OptionsBehavior.Editable = false;
            }
            Biencucbo.hdpt = 2;

        }


        // thay đổi
        private void gridView1_CellValueChanged(object sender, DevExpress.XtraGrid.Views.Base.CellValueChangedEventArgs e)
        {
            gridView1.PostEditor();
            if (e.Column.FieldName == "nguyente")
            {
                try
                {
                    gridView1.SetFocusedRowCellValue("thanhtien", (double.Parse(gridView1.GetFocusedRowCellValue("nguyente").ToString())) * (double.Parse(txttygia.Text)));
                }
                catch (Exception)
                {
                }
            }
        }

        //Phím Tắt
        private void gridView1_KeyDown(object sender, KeyEventArgs e)
        {
            if (Biencucbo.hdpt == 2)
                return;
            if (e.KeyCode == Keys.Insert)
            {
                gridView1.AddNewRow();

            }
            else if (e.KeyCode == Keys.Delete)
            {
                if (Biencucbo.hdpt == 1)
                {
                    try
                    {
                        pthuct ct = (from c in db.pthucts select c).Single(x => x.id == gridView1.GetFocusedRowCellValue("id").ToString());
                        db.pthucts.DeleteOnSubmit(ct);
                    }
                    catch
                    {

                    }
                }

                gridView1.DeleteRow(gridView1.FocusedRowHandle);
            }
        }
        //đối tượng
        private void txtiddt_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                var lst = (from a in db.doituongs select a).Single(t => t.id == txtiddt.Text);
                lbltendt.Text = lst.ten.ToString();
                txtdiachi.Text = lst.diachi.ToString();
            }
            catch (Exception)
            {
            }
        }

        //Dòng mới
        private void gridView1_InitNewRow(object sender, InitNewRowEventArgs e)
        {
            if (Biencucbo.hdpt == 1)
            {
                var ct = gridView1.GetFocusedRow() as pthuct;
                if (ct == null) return;

                int i = 0, k = 0;
                string a;

                k = gridView1.DataRowCount;
                a = txtid.Text + k;

                for (i = 0; i <= gridView1.DataRowCount - 1;)
                {
                    if (a == gridView1.GetRowCellValue(i, "id").ToString())
                    {
                        k = k + 1;
                        a = txtid.Text + k;
                        i = 0;
                    }
                    else
                    {
                        i++;
                    }
                }

                ct.idthu = txtid.Text;

                ct.diengiai = "";
                ct.idmuccp = "";
                ct.idcv = "";
                ct.thanhtien = 0.00;
                ct.id = a;
                ct.tiente = "KIP";
                ct.tygia = 1;
                ct.nguyente = 0;
            }

            else
            {
                gridView1.SetFocusedRowCellValue("diengiai", "");
                gridView1.SetFocusedRowCellValue("tygia", 1);
                gridView1.SetFocusedRowCellValue("idmuccp", "");
                gridView1.SetFocusedRowCellValue("tiente", "KIP");
                gridView1.SetFocusedRowCellValue("idcv", "");
                gridView1.SetFocusedRowCellValue("nguyente", 0);
            }
        }

        private void btnin_ItemClick_1(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                var lst = (from a in db.r_pthus where a.id == txtid.Text select a);
                r_pthu xtra = new r_pthu();
                xtra.DataSource = lst;
                xtra.ShowPreviewDialog();
            }
            catch
            {
            }
        }

        //đóng form
        private void f_pnhap_FormClosing(object sender, FormClosingEventArgs e)
        {
            if (Biencucbo.hdpt != 2)
            {
                var a = Lotus.MsgBox.ShowYesNoCancelDialog("Phiếu này chưa được lưu - Bạn có muốn lưu Phiếu này trước khi thoát không?");
                if (a == DialogResult.Yes)
                {
                    luu();
                }
                else if (a == DialogResult.Cancel) e.Cancel = true;
            }
        }

        private void gridView1_CustomDrawRowIndicator(object sender, RowIndicatorCustomDrawEventArgs e)
        {
            if (!gridView1.IsGroupRow(e.RowHandle)) //Nếu không phải là Group
            {
                if (e.Info.IsRowIndicator) //Nếu là dòng Indicator
                {
                    if (e.RowHandle < 0)
                    {
                        e.Info.ImageIndex = 0;
                        e.Info.DisplayText = string.Empty;
                    }
                    else
                    {
                        e.Info.ImageIndex = -1; //Không hiển thị hình
                        e.Info.DisplayText = (e.RowHandle + 1).ToString(); //Số thứ tự tăng dần
                    }
                    SizeF _Size = e.Graphics.MeasureString(e.Info.DisplayText, e.Appearance.Font); //Lấy kích thước của vùng hiển thị Text
                    Int32 _Width = Convert.ToInt32(_Size.Width) + 20;
                    BeginInvoke(new MethodInvoker(delegate { cal(_Width, gridView1); })); //Tăng kích thước nếu Text vượt quá
                }
            }
            else
            {
                e.Info.ImageIndex = -1;
                e.Info.DisplayText = string.Format("[{0}]", (e.RowHandle * -1)); //Nhân -1 để đánh lại số thứ tự tăng dần
                SizeF _Size = e.Graphics.MeasureString(e.Info.DisplayText, e.Appearance.Font);
                Int32 _Width = Convert.ToInt32(_Size.Width) + 20;
                BeginInvoke(new MethodInvoker(delegate { cal(_Width, gridView1); }));
            }
        }
        bool cal(Int32 _Width, GridView _View)
        {
            _View.IndicatorWidth = _View.IndicatorWidth < _Width ? _Width : _View.IndicatorWidth;
            return true;
        }

        private void btnmuccp_EditValueChanged(object sender, EventArgs e)
        {
            gridView1.PostEditor();
        }

        private void rsearchtiente1_EditValueChanged(object sender, EventArgs e)
        {
            try
            {

                gridView1.PostEditor();
                var lst = (from a in db.tientes select a).Single(t => t.tiente1 == gridView1.GetFocusedRowCellValue("tiente").ToString());
                if (lst == null) return;
                gridView1.SetFocusedRowCellValue("tygia", lst.tygia);
                gridView1.SetFocusedRowCellValue("thanhtien", int.Parse(gridView1.GetFocusedRowCellValue("nguyente").ToString()) * int.Parse(gridView1.GetFocusedRowCellValue("tygia").ToString()));
            }
            catch
            {
            }
        }

        private void f_pthu_Load(object sender, EventArgs e)
        {
            LanguageHelper.Translate(this);
            LanguageHelper.Translate(barManager1);

            changeFont.Translate(this);
            changeFont.Translate(barManager1);

            load();
        }

        private void txttiente_EditValueChanged(object sender, EventArgs e)
        {
            if (txttiente.Text != "")
            {
                var lst = (from a in db.tientes select a).FirstOrDefault(t => t.tiente1 == txttiente.Text);
                txttygia.Text = lst.tygia.ToString();

                for (int i = 0; i <= gridView1.RowCount - 1; i++)
                {
                    try
                    {
                        gridView1.SetRowCellValue(i, "thanhtien", double.Parse(gridView1.GetRowCellValue(i, "nguyente").ToString()) * double.Parse(txttygia.Text));
                    }
                    catch
                    {
                    }
                }
            }
        }
    }
}