using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DAL;
using BUS;
using ControlLocalizer;
using DevExpress.XtraEditors;
using Lotus.Libraries;
using DevExpress.XtraBars.Alerter;
using GUI.Properties;
using GUI.Libs;

namespace GUI
{
    public partial class f_Skin : Form
    {
        KetNoiDBDataContext db = new KetNoiDBDataContext();

        t_skinabc sk = new t_skinabc();
        public f_Skin()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            Skinht.Properties.DataSource = new DAL.KetNoiDBDataContext().t_skins;
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            if (Skinht.Text == "")
                return;
            sk.sua(Biencucbo.skin);
            f_main frm = new f_main();
            frm.Refresh();
            this.Close();

            ShowAlert.Alert_Change_Success(this);
        }

        private void f_Skin_Load(object sender, EventArgs e)
        {
            LanguageHelper.Translate(this);
            Biencucbo.skin2 = Biencucbo.skin;
        }

        private void Skinht_EditValueChanged(object sender, EventArgs e)
        {
            Biencucbo.skin = Skinht.Text;
            f_main frm = new f_main();
            frm.Refresh();
        }

        private void cancel_Click(object sender, EventArgs e)
        {
            Biencucbo.skin = Biencucbo.skin2;
            f_main frm = new f_main();
            frm.Refresh();
            this.Close(); 
        }
    }
}
