using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DAL;
using BUS;
using ControlLocalizer;
using GUI.Libs;

namespace GUI
{
    public partial class f_themsodo : Form
    {
        KetNoiDBDataContext db = new KetNoiDBDataContext();
        t_sodo sp = new t_sodo();
        public f_themsodo()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            var lst = from a in db.r_giasps where a.iddv == Biencucbo.donvi select a;
            txtidsp.Properties.DataSource = lst;

            if (Biencucbo.ngonngu.ToString() == "Vietnam")
            {
                gridColumn1.Caption = "Mã SP";
                gridColumn2.Caption = "Tên SP";
                gridColumn3.Caption = "ĐVT";
            }
            else //lao
            {
                gridColumn1.Caption = "ລະຫັດຜະລິດຕະພັນ";
                gridColumn2.Caption = "ຊື່ຜະລິດຕະພັນ";
                gridColumn3.Caption = "ຫົວໜ່ວຍຄິິດໄລ່";
            }
        }

        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            this.Close();
        }

        private void btnluu_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            int key = 1;
            if (txtidsp.Text == "" || txtvoibom.Text == "" || txtcotbom.Text == "")
            {
                Lotus.MsgBox.ShowWarningDialog("Thông tin chưa đầy đủ - Vui lòng kiểm tra lại!");
            }
            else
            {
                if (Biencucbo.hdsd == 0)
                {
                    var stt = (from a in db.sodocotboms where a.iddv == Biencucbo.donvi select a.stt).Max();
                    if (stt != null)
                    {
                        key = int.Parse(stt.ToString()) + 1;
                    }
                    //khong cho trung ID va Ten
                    var Lst = (from dt in db.sodocotboms where dt.id == Biencucbo.donvi + "_" + txtcotbom.Text + "_" + txtvoibom.Text select dt).ToList();

                    if (Lst.Count == 1)
                    {
                        Lotus.MsgBox.ShowErrorDialog("Thông tin đã tồn tại - Vui lòng kiểm tra lại");
                    }
                    else
                    {
                        sp.moi(Biencucbo.donvi + "_" + txtcotbom.Text + "_" + txtvoibom.Text, Biencucbo.donvi, txtcotbom.Text, txtvoibom.Text, txtidsp.Text,key);
                        this.Close();

                        ShowAlert.Alert_Add_Success(this);
                    }
                }

                else
                { 
                    sp.sua(Biencucbo.donvi + "_" + txtcotbom.Text + "_" + txtvoibom.Text, Biencucbo.donvi, txtcotbom.Text, txtvoibom.Text, txtidsp.Text);
                    this.Close();

                    ShowAlert.Alert_Edit_Success(this);
                }
            }
        }

        //load
        private void f_themsanpham_Load(object sender, EventArgs e)
        {
            LanguageHelper.Translate(this);
            LanguageHelper.Translate(barManager1);
            this.Text = LanguageHelper.TranslateMsgString("." + Name + "_title", "Thêm Sơ Đồ").ToString();

            changeFont.Translate(this);
            changeFont.Translate(barManager1);

            if (Biencucbo.hdsd == 1)
            { 
                var lst = new DAL.KetNoiDBDataContext().sodocotboms;

                var thucthi = (from k in lst select k).Single(t => t.id == Biencucbo.ma && t.iddv == Biencucbo.donvi);
                txtidsp.Text = thucthi.idsp;
                txtcotbom.Text = thucthi.cotbom;
                txtvoibom.Text = thucthi.voibom;
            }
        } 
    }
}
