using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DAL;
using BUS;
using ControlLocalizer;
using GUI.Libs;
using DevExpress.XtraEditors;

namespace GUI
{
    public partial class f_themgiaban : Form
    {
        KetNoiDBDataContext db = new KetNoiDBDataContext();
        t_gia sp = new t_gia();
        t_ls_gia ls_gia = new t_ls_gia();
        public f_themgiaban()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            txtidsp.Properties.DataSource = new DAL.KetNoiDBDataContext().sanphams;
            txtten.ReadOnly = true;
            txtdvt.ReadOnly = true;
            txtloai.ReadOnly = true;
            txtgiacu.ReadOnly = true;
            //txtidnv.ReadOnly = true;

            if (Biencucbo.ngonngu.ToString() == "Vietnam")
            {
                gridColumn1.Caption = "Mã SP";
                gridColumn2.Caption = "Tên SP";
                gridColumn3.Caption = "ĐVT";
            }
            else //lao
            {
                gridColumn1.Caption = "ລະຫັດຜະລິດຕະພັນ";
                gridColumn2.Caption = "ຊື່ຜະລິດຕະພັນ";
                gridColumn3.Caption = "ຫົວໜ່ວຍຄິິດໄລ່";
            }
        }

        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            this.Close();
        }

        private void btnluu_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (txtidsp.Text == "" || txtten.Text == "" || txtgia.Text == "" || txtdvt.Text == "")
            {
                Lotus.MsgBox.ShowWarningDialog("Thông tin chưa đầy đủ - Vui lòng kiểm tra lại!");
            }
            else
            {
                //khong cho trung ID va Ten
                var Lst = (from dt in db.giasps where dt.id == txtid.Text + "_" + Biencucbo.donvi select dt).ToList();

                if (Lst.Count == 1)
                {
                    Lotus.MsgBox.ShowErrorDialog("Sản phẩm này đã tồn tại, Vui Lòng Kiểm tra Lại");
                }
                else
                {
                    t_history hs = new t_history();
                    t_tudong td = new t_tudong();

                    db = new KetNoiDBDataContext();
                    try
                    {
                        string check = "TDG" + Biencucbo.donvi.Trim().ToString();
                        var lst1 = (from s in db.tudongs where s.maphieu == check select s).ToList();
                        
                        if (lst1.Count == 0)
                        {
                            int so;

                            so = 2;
                            td.themtudong(check, so);
                            txtid.Text = check + "_000001";
                            txt1.Text = "1";
                        }
                        else
                        {
                            var lst2 = (from s in db.tudongs where s.maphieu == check select s).Single();
                            int k;
                            //txt1.DataBindings.Clear();
                            txt1.Text = "";
                            txt1.Text = lst2.so.ToString();
                            //txt1.DataBindings.Add("text", lst1, "so");
                            k = 0;
                            k = Convert.ToInt32(txt1.Text);
                            string so0 = "";
                            if (k < 10)
                            {
                                so0 = "00000";
                            }
                            else if (k >= 10 & k < 100)
                            {
                                so0 = "0000";
                            }
                            else if (k >= 100 & k < 1000)
                            {
                                so0 = "000";
                            }
                            else if (k >= 1000 & k < 10000)
                            {
                                so0 = "00";
                            }
                            else if (k >= 10000 & k < 100000)
                            {
                                so0 = "0";
                            }
                            else if (k >= 100000)
                            {
                                so0 = "";
                            }
                            txtid.Text = check + "_" + so0 + k;

                            k = k + 1;

                            td.suatudong(check, k);
                        }
                    }
                    catch (Exception ex)
                    {
                        //XtraMessageBox.Show(ex.Message);
                    }


                    if (Biencucbo.hdgia == 0)
                    {
                        sp.moi(txtidsp.Text + "_" + Biencucbo.donvi, Biencucbo.donvi, txtidsp.Text.Trim(), double.Parse(txtgia.Text));
                        ls_gia.moi_sua(txtid.Text, txtidsp.Text, Biencucbo.donvi, double.Parse(txtgiacu.Text), double.Parse(txtgia.Text), DateTime.Now, Biencucbo.idnv, txtghichu.Text, long.Parse(txt1.Text));


                        this.Close();

                    }
                    else //sua
                    {
                        sp.sua(txtidsp.Text + "_" + Biencucbo.donvi, Biencucbo.donvi, txtidsp.Text.Trim(), double.Parse(txtgia.Text));
                        ls_gia.moi_sua(txtid.Text, txtidsp.Text, Biencucbo.donvi, double.Parse(txtgiacu.Text), double.Parse(txtgia.Text), DateTime.Now, Biencucbo.idnv, txtghichu.Text, long.Parse(txt1.Text));

                        this.Close();
                    }
                }
            }
        }

        //load
        private void f_themsanpham_Load(object sender, EventArgs e)
        {
            LanguageHelper.Translate(this);
            LanguageHelper.Translate(barManager1);
            this.Text = LanguageHelper.TranslateMsgString("." + Name + "_title", "Thay Đổi Giá Bán").ToString();

            changeFont.Translate(this);
            changeFont.Translate(barManager1);

            if (Biencucbo.hdgia == 1)
            {
                txtidsp.ReadOnly = true;
                txtten.ReadOnly = true;
                txtdvt.ReadOnly = true;
                txtloai.ReadOnly = true;
                txtgiacu.ReadOnly = true;

                var lst = new DAL.KetNoiDBDataContext().r_giasps;

                var thucthi = (from k in lst select k).Single(t => t.idsp == Biencucbo.ma && t.iddv == Biencucbo.donvi);
                txtidsp.Text = thucthi.idsp;
                txtgia.Text = thucthi.giaban.ToString();
                txtgiacu.Text = thucthi.giaban.ToString();
                txt1.Text = thucthi.id.ToString();

            }
        }

        private void txtid_EditValueChanged(object sender, EventArgs e)
        {
            //try
            //{
            //    //var lst = (from a in db.sanphams select a).Single(t => t.id == txtidsp.Text);

            //    var lst = (from a in db.sanphams
            //               //join b in db.giasps on a.id equals b.idsp into k

            //               //from k1 in k.DefaultIfEmpty()
            //                   // orderby k1.so descending
            //               select new
            //               {
            //                   a.id,
            //                   a.tensp,
            //                   a.dvt,
            //                   a.loai,
            //                   a.giaban,

            //               }).First(t => t.id == txtidsp.Text && t.iddv == Biencucbo.donvi);

            //    //var lst2 = (from a in lst where a.iddv == Biencucbo.donvi select a.so).Max();

            //    txtten.Text = lst.tensp;
            //    txtdvt.Text = lst.dvt;
            //    txtloai.Text = lst.loai;
            //    txtgiacu.Text = lst.giaban.ToString();
            //}
            //catch
            //{
            //    //var lst = (from a in db.sanphams select a).Single(t => t.id == txtidsp.Text);
            //    //txtten.Text = lst.tensp;
            //    //txtdvt.Text = lst.dvt;
            //    //txtloai.Text = lst.loai;
            //    //txtgiacu.Text = lst.giaban.ToString();
            //}

            if (Biencucbo.hdgia == 0)//them
            {
                //khong cho trung ID va Ten
                var Lst = (from dt in db.giasps where dt.id == txtidsp.Text + "_" + Biencucbo.donvi select dt).ToList();

                if (Lst.Count == 1)
                {
                    Lotus.MsgBox.ShowErrorDialog("Sản phẩm này đã tồn tại, Vui Lòng Kiểm tra Lại");
                    return;
                }
            }

            try
            {
                var lst = (from a in db.sanphams select a).Single(t => t.id == txtidsp.Text);

                txtten.Text = lst.tensp;
                txtdvt.Text = lst.dvt;
                txtloai.Text = lst.loai;
                txtgiacu.Text = lst.giaban.ToString();
            }
            catch
            {
            }
        }
    }
}