using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DAL;
using BUS;
using ControlLocalizer;
using GUI.Libs;

namespace GUI
{
    public partial class f_themkiemke : Form
    {
        KetNoiDBDataContext db = new KetNoiDBDataContext();
        t_gia sp = new t_gia();
        public f_themkiemke()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            txtid.Properties.DataSource = new DAL.KetNoiDBDataContext().sanphams;
            txtten.ReadOnly = true;
            txtdvt.ReadOnly = true;
          
        }

        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            this.Close();
        }

        private void btnluu_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (txtid.Text == "" || txtten.Text == "" || txtkiemke.Text == "" || txtdvt.Text == "")
            {
                Lotus.MsgBox.ShowWarningDialog("Thông tin chưa đầy đủ - Vui lòng kiểm tra lại!");
            }
            else
            {
                {
                    sp.suakiemke(txtid.Text + "_" + Biencucbo.donvi, Biencucbo.donvi, txtid.Text.Trim(), float.Parse(txtkiemke.Text));
                    this.Close();

                    ShowAlert.Alert_Edit_Success(this);
                }
            }
        }

        //load
        private void f_themsanpham_Load(object sender, EventArgs e)
        {
            LanguageHelper.Translate(this);
            LanguageHelper.Translate(barManager1);
            this.Text = LanguageHelper.TranslateMsgString("." + Name + "_title", "Số Lượng Kiểm Kê").ToString();

            changeFont.Translate(this);
            changeFont.Translate(barManager1);

            txtid.ReadOnly = true;
            txtten.ReadOnly = true;
            txtdvt.ReadOnly = true;

            var lst = new DAL.KetNoiDBDataContext().r_giasps;

            var thucthi = (from k in lst select k).Single(t => t.idsp == Biencucbo.ma && t.iddv == Biencucbo.donvi);
            txtid.Text = thucthi.idsp;
            txtkiemke.Text = thucthi.kiemke.ToString();

        }

        private void txtid_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                var lst = (from a in db.sanphams select a).Single(t => t.id == txtid.Text);

                txtten.Text = lst.tensp;
                txtdvt.Text = lst.dvt;
                
            }
            catch
            {
            }
        }
    }
}
